### ISSUE TITLE
Example BS-colouring

### ISSUE THREAD

**Issue by avilella** [dariober/ASCIIGenome#57]
Hi @dariober ,

I am starting to use ASCIIGenome and would like to produce screenshots with BS-colouring. I couldn't find the notation in the documentation to do that. Can you post an example here?

Example command-line I am using:

```
ASCIIGenome -ni -r chr9:136946101-123456781 -x "save /data/group/test/TEST_Run001/TEST_Run001-12345678/TST59_70_1b-12345678/TST59-70-1b_S1_L001_R1_001.1.cutB_bismark_bt2_se.dedupled.sorted.bam.chr9:136946101-123456781.ascii.pdf" /data/group/test/TEST_Run001/TEST_Run001-12345678/TST59_70_1b-12345678/TST59-70-1b_S1_L001_R1_001.1.cutB_bismark_bt2_se.dedupled.sorted.bam 1>/dev/null
```

**Comment by dariober** [comment]
Hello- Sorry I haven't replied to this before. I think what you want to do is:

```
ASCIIGenome -ni -r chr7:5560001 -fa genome.fa -x 'BSseq && save bs.%r.pdf' aln.bam > /dev/null
```

To enable BS colouring you need the pass the reference fasta file (indexed with e.g. `samtools faidx ref.fa`, if the index is not found ASCIIGenome will create a temporary indexed). Then you need the `BSseq` option inside `-x` to tell ASCIIGenome to interpret bases as BS-Seq data. Finally save the screenshot as pdf (here the string %r is expanded to the current genomic coordinates).

Note also that BS colouring is visible only when you zoom in a region enough so that 1 bp correspond to 1 character of text.

Hope this helps!
