### ISSUE TITLE
multiple tracks from list of http bigwig (bw) urls

### ISSUE THREAD

**Issue by avilella** [dariober/ASCIIGenome#60]
Hi @dariober again,

I was wondering what would be the command-line to load a list of bigwig files as a list of tracks from a list of http urls.

I tried the command-line below with a list of 12 URLs, but ASCIIGenome only loaded one of them:

```
$ wc -l /bi/group/cegx/TSTX_Run357/TSTX_Run357.dnanexus.idxsession
12 /bi/group/cegx/TSTX_Run357/TSTX_Run357.dnanexus.idxsession
$ cat /bi/group/cegx/TSTX_Run357/TSTX_Run357.dnanexus.idxsession | xargs echo | xargs ASCIIGenome -fa $fa

```
Sorry if this is in the documentation and I overlooked it.
Any ideas? Thx.

**Comment by dariober** [comment]
Hi- If I understand correctly, you a file with URLs to be loaded. If this file has one URL per line, put these URLs in a Bash variable and give this variable to ASCIIGenome. E.g.:

```
cat urls.txt
http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/byDataType/signal/jan2011/bigwig/wgEncodeBroadHistoneGm12878ControlStdAln_2Reps.norm5.rawsignal.bw
http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/byDataType/signal/jan2011/bigwig/wgEncodeBroadHistoneGm12878CtcfStdAln_2Reps.norm5.rawsignal.bw
http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/byDataType/signal/jan2011/bigwig/wgEncodeBroadHistoneGm12878H2azStdAln_2Reps.norm5.rawsignal.bwC02QD4
...
```

Put these URLs in a variable and load:

```
urls=`cat urls.txt`
ASCIIGenome $urls 
```

Edit as required if the file is not just one URL per line, but the point is just to construct a variable with URLs. 

Note that to connect to 12 files it will take a minute or two but after that it should go fairly smooth.

This is not documented since after all it's a Bash trick, nothing to do with ASCIIGenome.
