### ISSUE TITLE
Is there a way to scroll up and down to view all reads in ASCIIgenome?

### ISSUE THREAD

**Issue by zhengxinchang** [dariober/ASCIIGenome#92]
Hi,
this is an excellent software that I need exactly.
but I wonder to know that Is there a way to scroll up and down to view all reads in ASCIIgenome?
set trackHeight to a higher number can not view all reads in a high coverage, and zoom out also does not work because the reads will be present by <<<< or >>>>>

thanks
xinchang zheng

**Comment by dariober** [comment]
Thanks for your interest! 
If I understand your question correctly, you want to show all the aligned reads at single base resolution (i.e. 1 bp = 1 character). For speed of processing and for (usually) better visualization, reads are downsampled to 2000. 

So what you want is to increase the number of reads downsampled. You can do this with `setConfig max_reads_in_stack 20000` (replace 20000 with your choice). Of course, you have to increase also `trackHeight`. 

See if this example helps. First I create a bam file with lots of reads in a region, `test_data/ds051.actb.bam` is ASCIIGenome repository:

```
samtools merge tmp.bam test_data/ds051.actb.bam test_data/ds051.actb.bam test_data/ds051.actb.bam
samtools index tmp.bam
```

Now I load `tmp.bam`, move to the high coverage region, reset `max_reads_in_stack` and `trackHeight`, save the screenshot as txt:

```
ASCIIGenome -r chr7:5567031-5567121 -x 'setConfig max_reads_in_stack 20000 && trackHeight 10000 @ && save tmp2.txt' -ni tmp.bam > /dev/null
```

The output tmp2.txt has 2874 lines. If you execute the command above without `setConfig max_reads_in_stack 20000` you get only 1218 because of the downsampling.

A couple of notes though:

* It will be slow with lots of reads

* Set or reset  `trackHeight` **after** `setConfig`. This is because reads are cached and you need to refresh the cache (this should be fixed).

**Comment by zhengxinchang** [comment]
thank you for your help. It worked !

best 

xinchang zheng
